# Main background
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#E5E5E5"

# Title color for boxes
theme[title]="#D9D9D9"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#FFFFFF"

# Background color of selected items
theme[selected_bg]="#2E2E2E"

# Foreground color of selected items
theme[selected_fg]="#E5E5E5"

# Color of inactive/disabled text
theme[inactive_fg]="#7A7A7A"

# Color of text appearing on top of graphs
theme[graph_text]="#E5E5E5"

# Misc colors for processes box
theme[proc_misc]="#B2B2B2"

# Cpu box outline color
theme[cpu_box]="#474747"

# Memory/disks box outline color
theme[mem_box]="#474747"

# Net up/down box outline color
theme[net_box]="#474747"

# Processes box outline color
theme[proc_box]="#474747"

# Box divider line and small boxes line color
theme[div_line]="#474747"

# Temperature graph colors
theme[temp_start]="#7A7A7A"
theme[temp_mid]="#B2B2B2"
theme[temp_end]="#E5E5E5"

# CPU graph colors
theme[cpu_start]="#5E5E5E"
theme[cpu_mid]="#999999"
theme[cpu_end]="#E5E5E5"

# Mem/Disk free meter
theme[free_start]="#5E5E5E"
theme[free_mid]="#999999"
theme[free_end]="#E5E5E5"

# Mem/Disk cached meter
theme[cached_start]="#5E5E5E"
theme[cached_mid]="#999999"
theme[cached_end]="#E5E5E5"

# Mem/Disk available meter
theme[available_start]="#5E5E5E"
theme[available_mid]="#999999"
theme[available_end]="#E5E5E5"

# Mem/Disk used meter
theme[used_start]="#5E5E5E"
theme[used_mid]="#999999"
theme[used_end]="#E5E5E5"

# Download graph colors
theme[download_start]="#B2B2B2"
theme[download_mid]="#7A7A7A"
theme[download_end]="#474747"

# Upload graph colors
theme[upload_start]="#474747"
theme[upload_mid]="#999999"
theme[upload_end]="#E5E5E5"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#E5E5E5"
theme[process_mid]="#B2B2B2"
theme[process_end]="#7A7A7A"